version: '3.5'
volumes:
  node_modules:
services:
  app:
    stdin_open: true
    image: node:12.16.1-alpine
    working_dir: /app
    command: sh -c "yarn && yarn start"
    environment:
      - NODE_ENV=development
    ports:
      - 51101:3000
    volumes:
      - node_modules:/app/node_modules
      - .:/app
